name: official-docs-instructions


services:
  functionapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: docker.io/josephaw1022/my-quarkus-azure-function:2025-09.01
    container_name: quarkus-azure-function
    environment:
      FUNCTIONS_WORKER_RUNTIME: java
      FUNCTIONS_EXTENSION_VERSION: "~4"
    ports:
      - "8080:80"
    restart: unless-stopped