name: azure-emulators-stack
services:
  eventhubs-emulator:
    container_name: eventhubs-emulator
    image: mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest
    pull_policy: always
    volumes:
      - "./ConfigFiles/EventHub:/Eventhubs_Emulator/ConfigFiles:ro,Z"
    ports:
      - "5672:5672"
      - "9092:9092"
      - "5300:5300"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - azurite
    networks:
      bus-net:
        aliases: [ "eventhubs-emulator" ]

  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite:latest
    pull_policy: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      bus-net:
        aliases: [ "azurite" ]

  servicebus-emulator:
    container_name: servicebus-emulator
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "./ConfigFiles/ServiceBus:/ServiceBus_Emulator/ConfigFiles:ro,Z"
    ports:
      - "5673:5672"
      - "5301:5300"
    environment:
      SQL_SERVER: mssql
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
      ACCEPT_EULA: "${ACCEPT_EULA}"
      SQL_WAIT_INTERVAL: "${SQL_WAIT_INTERVAL:-15}"
    depends_on:
      - mssql
    networks:
      bus-net:
        aliases: [ "sb-emulator" ]

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "${ACCEPT_EULA}"
      MSSQL_SA_PASSWORD: "${MSSQL_SA_PASSWORD}"
    networks:
      bus-net:
        aliases: [ "mssql" ]

    volumes:
      - mssql-data:/var/opt/mssql
    cap_add:
      - SYS_PTRACE
    privileged: true

volumes:
  mssql-data:

networks:
  bus-net:
