apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - k8s-deploy-funcs.yaml

patches:
  - target:
      kind: Service
      name: azure-func-container-dotnet9-http
      namespace: deploy-funcs
    patch: |-
      - op: replace
        path: /spec/type
        value: NodePort
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30080
